spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=rider-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-shy-frost-ads427j3-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
