version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: rider-postgres
    environment:
      POSTGRES_DB: rider_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rider-postgres-data:/var/lib/postgresql/data

volumes:
  rider-postgres-data: