apiVersion: v2
name: cab-booking
description: A Helm chart for Cab Booking System Microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 20.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
