name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      run: |
        # Build all services
        ./mvnw clean package -DskipTests
        
        # Build and push Docker images
        docker build -t dhruti313/cab-auth-service:${{ github.sha }} ./auth-service
        docker build -t dhruti313/cab-rider-service:${{ github.sha }} ./rider-service
        docker build -t dhruti313/cab-driver-service:${{ github.sha }} ./driver-service
        docker build -t dhruti313/cab-trip-service:${{ github.sha }} ./trip-service
        
        docker push dhruti313/cab-auth-service:${{ github.sha }}
        docker push dhruti313/cab-rider-service:${{ github.sha }}
        docker push dhruti313/cab-driver-service:${{ github.sha }}
        docker push dhruti313/cab-trip-service:${{ github.sha }}
    
    - name: Deploy to Kubernetes
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
        # Update Kubernetes deployments with new image tags
        kubectl set image deployment/auth-service auth-service=dhruti313/cab-auth-service:${{ github.sha }}
        kubectl set image deployment/rider-service rider-service=dhruti313/cab-rider-service:${{ github.sha }}
        kubectl set image deployment/driver-service driver-service=dhruti313/cab-driver-service:${{ github.sha }}
        kubectl set image deployment/trip-service trip-service=dhruti313/cab-trip-service:${{ github.sha }}
